// All default game content, extracted from the original gamenight.html.
// Consumed by scripts/seed.ts to populate Supabase.

import type { GameType } from "./supabase";

export interface RegistrySeed {
  id: string;
  emoji: string;
  name: string;
  type: GameType;
}

export const BUILTIN_GAMES: RegistrySeed[] = [
  { id: "trivia", emoji: "🧠", name: "Trivia", type: "trivia" },
  { id: "wyr", emoji: "⚡", name: "Would You Rather", type: "simple" },
  { id: "agree", emoji: "🗣️", name: "Agree or Disagree", type: "simple" },
  { id: "beige", emoji: "🏳️", name: "Beige Flags", type: "simple" },
  { id: "avoid", emoji: "🚫", name: "Avoid My Answer", type: "avoid" },
  { id: "vote", emoji: "🗳️", name: "Most Likely To", type: "simple" },
  { id: "lnt", emoji: "🌙", name: "Late Night Talks", type: "simple" },
  { id: "couples", emoji: "💑", name: "Couples Questions", type: "simple" },
  { id: "podcast", emoji: "🎙️", name: "Podcast Questions", type: "simple" },
  { id: "uncomfortable", emoji: "😬", name: "Uncomfortable Questions", type: "simple" },
  { id: "categories", emoji: "📋", name: "Categories", type: "simple" },
  { id: "password", emoji: "🔑", name: "Password", type: "simple" },
  { id: "overrated", emoji: "📊", name: "Overrated or Underrated", type: "simple" },
  { id: "contact", emoji: "📞", name: "Contact", type: "rules" },
  { id: "twentyq", emoji: "❓", name: "20 Questions", type: "simple" },
  { id: "wavelength", emoji: "🌊", name: "Wavelength", type: "wavelength" },
  { id: "fivesec", emoji: "⏱️", name: "5 Second Challenge", type: "fivesec" },
];

export const triviaData: { q: string; a: string; type: string }[] = [
  { q: "What is the chemical symbol for Mercury?", a: "Hg", type: "quickfire" },
  { q: "What is 12 squared?", a: "144", type: "quickfire" },
  { q: "What Pokémon type is Pikachu?", a: "Electric", type: "quickfire" },
  { q: "What is the largest bone in the human body?", a: "Femur", type: "quickfire" },
  { q: "What is the capital of Japan?", a: "Tokyo", type: "quickfire" },
  { q: "Which blood type is the universal donor?", a: "O Negative", type: "quickfire" },
  { q: "What is the fastest land animal?", a: "Cheetah", type: "quickfire" },
  { q: "How many hearts does an octopus have?", a: "3", type: "quickfire" },
  { q: "Who wrote To Kill a Mockingbird?", a: "Harper Lee", type: "quickfire" },
  { q: "What gas do humans exhale?", a: "Carbon dioxide", type: "quickfire" },
  { q: "What is the capital of Pakistan?", a: "Islamabad", type: "quickfire" },
  { q: "What year did WWI begin?", a: "1914", type: "quickfire" },
  { q: "What is the largest mammal in the world?", a: "Blue whale", type: "quickfire" },
  { q: "How many permanent teeth do most adults have?", a: "32", type: "quickfire" },
  { q: "Who plays Ken in Barbie (2023)?", a: "Ryan Gosling", type: "quickfire" },
  { q: "Name one of the 7 dwarfs.", a: "Doc, Grumpy, Happy, Sleepy, Bashful, Sneezy, Dopey", type: "quickfire" },
  { q: "What is the square root of 144?", a: "12", type: "quickfire" },
  { q: "Who sang Never Gonna Give You Up?", a: "Rick Astley", type: "quickfire" },
  { q: "What do you call a number with 100 zeros?", a: "Googol", type: "quickfire" },
  { q: "Who plays Serena Van Der Woodsen in Gossip Girl?", a: "Blake Lively", type: "quickfire" },
  { q: "What was the first animal ever cloned?", a: "Sheep (Dolly)", type: "quickfire" },
  { q: "What is the chemical symbol for gold?", a: "Au", type: "quickfire" },
  { q: "In which sport would you perform a slam dunk?", a: "Basketball", type: "quickfire" },
  { q: "Who is known as the King of Pop?", a: "Michael Jackson", type: "quickfire" },
  { q: "What is the capital of Australia?", a: "Canberra", type: "quickfire" },
  { q: "Which famous artist was claimed to be the biggest CO2 Polluter of 2023?\nA) Taylor Swift  B) Biggie Smalls  C) Snoop Dogg  D) Olivia Rodrigo", a: "A) Taylor Swift", type: "mc" },
  { q: "Which is the most streamed song of the 2010s?\nA) Shape of You – Ed Sheeran  B) One Dance – Drake  C) Closer – Chainsmokers  D) Rolling in the Deep – Adele", a: "A) Shape of You – Ed Sheeran", type: "mc" },
  { q: "Who did Elon Musk replace as CEO of Twitter?\nA) Jack Dorsey  B) Linda Yaccharino  C) Parag Agrawal  D) Ravindra Sinkar", a: "C) Parag Agrawal", type: "mc" },
  { q: "What do cows drink?\nA) Pink Moscato  B) Milk  C) Water  D) Piña Coladas", a: "C) Water", type: "mc" },
  { q: "In what city are the 2024 Summer Olympics held?\nA) Tokyo  B) Rio  C) London  D) Paris", a: "D) Paris", type: "mc" },
  { q: "Which of the following is NOT the real name of a celebrity baby?\nA) Audio  B) Wolf Webster  C) Moroccan  D) Canada", a: "D) Canada", type: "mc" },
  { q: "Who won the first Oscar for Oppenheimer?\nA) Robert Downey Jr.  B) Cillian Murphy  C) Chris Evans  D) Ryan Gosling", a: "B) Cillian Murphy", type: "mc" },
  { q: "Which planet has the most moons?\nA) Jupiter  B) Saturn  C) Uranus  D) Neptune", a: "B) Saturn", type: "mc" },
  { q: "What was the most downloaded app of 2016?\nA) TikTok  B) Instagram  C) Snapchat  D) Twitter", a: "C) Snapchat", type: "mc" },
  { q: "Which Ivy League college comes first alphabetically?\nA) Columbia  B) Brown  C) Cornell  D) Dartmouth", a: "B) Brown University", type: "mc" },
  { q: "How many stitches did Abhi get on his 18th birthday?", a: "9", type: "friends" },
  { q: "What does Abhi and Shreya's anniversary date?", a: "12/2/15", type: "friends" },
  { q: "What unique facial expression does Manisha randomly make?", a: "Cartoon smile", type: "friends" },
  { q: "What clothing brand does Tejas always wear?", a: "Brooks Brothers", type: "friends" },
  { q: "What is Nikhil's favorite basketball team?", a: "Boston Celtics", type: "friends" },
  { q: "What was the name of the alcoholic drink used at girls night?", a: "Screwdrivers", type: "friends" },
  { q: "What is Tejas's job?", a: "Data Architect", type: "friends" },
  { q: "What 15 seed Ivy League school did Kashish have making a deep run in March Madness?", a: "Princeton", type: "friends" },
  { q: "What restaurant is closest to the Aspire?", a: "Efe's", type: "friends" },
  { q: "What was the original name of Rutgers University?", a: "Queens College", type: "friends" },
  { q: "Cormac and Manisha's anniversary date?", a: "3/9/22", type: "friends" },
  { q: "Tejas and Isha's anniversary date?", a: "5/30/22", type: "friends" },
  { q: "Nikhil and Kashish's anniversary date?", a: "9/17/22", type: "friends" },
  { q: "What is Eswar's alter ego's name?", a: "Edward Shark", type: "friends" },
  { q: "What did Hershey think a vasectomy initially was?", a: "Cutting off the penis", type: "friends" },
  { q: "Who recorded the video of Eswar and Abhi breaking the door?", a: "Yaashi", type: "friends" },
  { q: "What color was Sid's new bong in senior year?", a: "Orange", type: "friends" },
  { q: "Who was the first woman to win a Nobel Prize, and in what field?", a: "Marie Curie, Physics (1903)", type: "medium" },
  { q: "Which element has the chemical symbol 'W'?", a: "Tungsten", type: "medium" },
  { q: "What was the name of Charles Darwin's ship?", a: "HMS Beagle", type: "medium" },
  { q: "In Greek mythology, who was condemned to hold up the sky?", a: "Atlas", type: "medium" },
  { q: "Which chess piece can only move diagonally?", a: "Bishop", type: "medium" },
  { q: "What year did the Berlin Wall fall?", a: "1989", type: "medium" },
  { q: "Who built Machu Picchu?", a: "The Inca Empire", type: "medium" },
  { q: "What country has the only flag that is not rectangular?", a: "Nepal", type: "medium" },
  { q: "Which animal has the longest lifespan?", a: "Bowhead whale", type: "medium" },
  { q: "Who was the first Emperor of China?", a: "Qin Shi Huang", type: "medium" },
  { q: "What is the national animal of Scotland?", a: "Unicorn", type: "medium" },
  { q: "What animal has pink milk?", a: "Hippo", type: "medium" },
  { q: "Which is the only body part fully grown from birth?", a: "Eyes", type: "medium" },
  { q: "What year was YouTube founded?", a: "2005", type: "medium" },
  { q: "What is the most expensive spice in the world?", a: "Saffron", type: "medium" },
  { q: "Who invented the World Wide Web?", a: "Tim Berners-Lee", type: "medium" },
  { q: "What was Google's original name?", a: "Backrub", type: "medium" },
  { q: "Which African country has the most pyramids?", a: "Sudan", type: "medium" },
  { q: "What is the most abundant gas in Earth's atmosphere?", a: "Nitrogen", type: "medium" },
  { q: "What year was the first email sent?", a: "1971", type: "medium" },
  { q: "What is the only bird that can fly backwards?", a: "Hummingbird", type: "hard" },
  { q: "Before founding Facebook, what website did Zuckerberg create to compare attractiveness?", a: "Facemash", type: "hard" },
  { q: "What element has the symbol 'Sb'?", a: "Antimony", type: "hard" },
  { q: "Who was the first man to reach the South Pole?", a: "Roald Amundsen", type: "hard" },
  { q: "Which country was formerly known as Ceylon?", a: "Sri Lanka", type: "hard" },
  { q: "Who painted The Birth of Venus?", a: "Sandro Botticelli", type: "hard" },
  { q: "What is the capital of Mongolia?", a: "Ulaanbaatar", type: "hard" },
  { q: "Which Shakespeare play features Rosencrantz and Guildenstern?", a: "Hamlet", type: "hard" },
  { q: "How many consecutive points did LeBron score in Game 5 of the 2007 ECF?", a: "25", type: "hard" },
  { q: "What was Usain Bolt's 100m time at the 2008 Olympics (to nearest hundredth)?", a: "9.58 seconds", type: "hard" },
  { q: "Which Bollywood film was India's first Oscar submission?", a: "Mother India (1957)", type: "hard" },
  { q: "What is the legal term for a voluntary written statement made under oath?", a: "Affidavit", type: "hard" },
  { q: "What mathematician is known as the Father of Geometry?", a: "Euclid", type: "hard" },
  { q: "In what year did Pakistan win the Cricket World Cup, and who captained them?", a: "1992, Imran Khan", type: "hard" },
  { q: "What is Hippopotomonstrosesquippedaliophobia?", a: "Fear of long words", type: "hard" },
  { q: "What is the atomic number for Oxygen?", a: "8", type: "hard" },
  { q: "Which chess piece moves in an L-shape?", a: "Knight", type: "hard" },
  { q: "What is the rarest blood type?", a: "AB Negative", type: "hard" },
  { q: "I speak without a mouth and hear without ears. I have no body, but I come alive with wind. What am I?", a: "An echo", type: "riddle" },
  { q: "The more you take, the more you leave behind. What am I?", a: "Footsteps", type: "riddle" },
  { q: "I have cities, but no houses live there. I have mountains, but no trees grow there. I have water, but no fish swim there. What am I?", a: "A map", type: "riddle" },
  { q: "What has to be broken before you can use it?", a: "An egg", type: "riddle" },
  { q: "I'm light as a feather, but the strongest person can't hold me for more than a few minutes. What am I?", a: "Breath", type: "riddle" },
  { q: "What gets wetter the more it dries?", a: "A towel", type: "riddle" },
  { q: "What has hands but can't clap?", a: "A clock", type: "riddle" },
  { q: "A man walks into a restaurant and orders albatross soup. After one sip he goes home and kills himself. Why?", a: "He was stranded on an island with his wife — the 'albatross soup' was actually her. He realized what he had eaten.", type: "riddle" },
  { q: "Forward I'm heavy. Backward I'm not. What am I?", a: "A ton", type: "riddle" },
  { q: "What 5-letter word becomes shorter when you add two letters to it?", a: "Short (short + er = shorter)", type: "riddle" },
  { q: "What number does Patrick Mahomes wear?", a: "15", type: "quickfire" },
  { q: "Which singer had a 2011 hit with Born This Way?", a: "Lady Gaga", type: "quickfire" },
  { q: "Who is the Roman goddess of love?", a: "Venus", type: "quickfire" },
  { q: "Name one of the 2 biggest airports in New York.", a: "JFK or LGA", type: "quickfire" },
  { q: "What planet is considered the outermost planet in our solar system?", a: "Neptune", type: "quickfire" },
  { q: "What is the 4th letter in the Greek alphabet?", a: "Delta", type: "quickfire" },
  { q: "What software company is headquartered in Redmond, Washington?", a: "Microsoft", type: "quickfire" },
  { q: "How many dots appear on a pair of dice?", a: "42", type: "quickfire" },
  { q: "How many faces does a dodecahedron have?", a: "12", type: "quickfire" },
  { q: "Aureolin is a shade of what color?", a: "Yellow", type: "quickfire" },
  { q: "What is the smallest US state by area?", a: "Rhode Island", type: "quickfire" },
  { q: "What is the capital of Nevada?", a: "Carson City", type: "quickfire" },
  { q: "How many stars are on the Chinese flag?", a: "5", type: "quickfire" },
  { q: "Who discovered the Earth revolves around the sun?", a: "Nicolaus Copernicus", type: "quickfire" },
  { q: "What was the name of the peace treaty that ended WWI?", a: "Treaty of Versailles", type: "quickfire" },
  { q: "Who was assassinated on June 28, 1914, setting off WWI?", a: "Archduke Franz Ferdinand of Austria", type: "quickfire" },
  { q: "What is Harvey's secretary's name in Suits?", a: "Donna", type: "quickfire" },
  { q: "What do you call a camel with only one hump?", a: "Dromedary", type: "quickfire" },
  { q: "In what year did Facebook originally launch?", a: "2004", type: "quickfire" },
  { q: "What does DNA stand for?", a: "Deoxyribonucleic acid", type: "quickfire" },
  { q: "How many wives did King Henry VIII have?", a: "6", type: "quickfire" },
  { q: "In the context of email, what does CC stand for?", a: "Carbon copy", type: "quickfire" },
  { q: "\"Life is like a box of chocolates\" is a quote from what movie?", a: "Forrest Gump", type: "quickfire" },
  { q: "What does BMW stand for in English?", a: "Bavarian Motor Works", type: "quickfire" },
  { q: "Which European nation is said to have invented hot dogs?", a: "Germany", type: "quickfire" },
  { q: "Which country is famous for chocolate and home to Toblerone?", a: "Switzerland", type: "quickfire" },
  { q: "JFK was assassinated in which city?", a: "Dallas, TX", type: "quickfire" },
  { q: "What year was JFK assassinated?", a: "1963", type: "quickfire" },
  { q: "What is P Diddy's real name?", a: "Sean Combs", type: "quickfire" },
  { q: "Who wrote Charlotte's Web?", a: "E.B. White", type: "quickfire" },
  { q: "What is the tallest building in the world?", a: "Burj Khalifa", type: "quickfire" },
  { q: "Which American president was involved in the Watergate scandal?", a: "Richard Nixon", type: "quickfire" },
  { q: "What does ANC stand for in South Africa?", a: "African National Congress", type: "quickfire" },
  { q: "In 1888, which unidentified serial killer terrorized Whitechapel, London?", a: "Jack the Ripper", type: "quickfire" },
  { q: "What is a group of frogs called?", a: "An army", type: "quickfire" },
  { q: "What is the name of the largest living reptile?", a: "Saltwater crocodile", type: "quickfire" },
  { q: "Name one of the 2 founders of Google.", a: "Larry Page or Sergey Brin", type: "quickfire" },
  { q: "What is the tiny piece at the end of a shoelace called?", a: "Aglet", type: "quickfire" },
  { q: "What is the human body's heaviest organ?", a: "Skin", type: "quickfire" },
  { q: "Where is the Mona Lisa on display?", a: "The Louvre Museum", type: "quickfire" },
  { q: "What plant is tequila made from?", a: "Agave", type: "quickfire" },
  { q: "What country is known as the 'land of the rising sun'?", a: "Japan", type: "quickfire" },
  { q: "What does BBC stand for?", a: "British Broadcasting Corporation", type: "quickfire" },
  { q: "Which brand invented energy drinks?", a: "Red Bull", type: "quickfire" },
  { q: "'Think different' is the slogan for which brand?", a: "Apple", type: "quickfire" },
  { q: "What actor plays Barry Allen in The Flash?", a: "Grant Gustin", type: "quickfire" },
  { q: "In what year did Pakistan win the Cricket World Cup?", a: "1992", type: "medium" },
  { q: "Who captained Pakistan to the 1992 Cricket World Cup win?", a: "Imran Khan", type: "medium" },
  { q: "How old was Kapil Dev when he captained India to its first-ever World Cup win?", a: "24", type: "medium" },
  { q: "In ballet, what is the term for 'bending at the knees'?", a: "Plié", type: "medium" },
  { q: "What is the name of the French luxury fashion house known for its monogrammed handbags?", a: "Louis Vuitton", type: "medium" },
  { q: "What is the largest living reptile?", a: "Saltwater crocodile", type: "medium" },
  { q: "What map in Mario Kart is known for having 7 laps instead of 3?", a: "Baby Park", type: "medium" },
  { q: "When is National Ice Cream Month?", a: "July", type: "medium" },
  { q: "What month is associated with the Topaz birthstone?", a: "November", type: "medium" },
  { q: "Which color gives its name to the region of spacetime nothing can escape?", a: "Black (Black hole)", type: "medium" },
  { q: "Which Ivy League college has an unofficial mascot named Peggy the Keg?", a: "Dartmouth", type: "hard" },
  { q: "In the insurance business, what is a person called who analyzes statistics to calculate risk and price premiums?", a: "Actuary", type: "hard" },
  { q: "What team initially drafted Luka Dončić?", a: "Atlanta Hawks", type: "hard" },
  { q: "Who was OU's quarterback in 2017?", a: "Baker Mayfield", type: "hard" },
  { q: "How many zeroes does a googolplex have?", a: "A googol (10^100) zeroes", type: "hard" },
  { q: "How tall is Bowser according to Game Rant, to the closest foot?", a: "10 feet", type: "hard" },
  { q: "Who called Bellatrix Lestrange a bitch in Harry Potter?", a: "Molly Weasley", type: "hard" },
  { q: "What is the snake language called in Harry Potter?", a: "Parseltongue", type: "hard" },
  { q: "What academy did Percy Jackson go to?", a: "Yancy Academy", type: "hard" },
  { q: "What is the full name of the last episode of Avatar: The Last Airbender?", a: "Sozin's Comet - Part 4: Avatar Aang", type: "hard" },
  { q: "What is the name of Light Yagami's sister in Death Note?", a: "Sayu", type: "hard" },
  { q: "In Kuch Kuch Hota Hai, name one of the 2 main actresses' full character names.", a: "Tina Malhotra or Anjali Sharma", type: "hard" },
  { q: "What channel has the 2nd most subscribers on YouTube?", a: "T-Series", type: "hard" },
  { q: "Name 2 legendary Pokémon from Generation 1.", a: "Articuno, Moltres, Zapdos, Mew, or Mewtwo", type: "hard" },
  { q: "Who has Trump recently appointed as director of the FBI?", a: "Kash Patel", type: "hard" },
  { q: "What animal does Hershey have a fetish for?", a: "Llamas", type: "friends" },
  { q: "What car does Abhi have?", a: "Subaru", type: "friends" },
  { q: "Who broke the bong first?", a: "Het", type: "friends" },
];

export const wyrData: string[] = [
  "Compete in the Special Olympics as a perfectly healthy person OR go to a children's hospital dressed as the Grim Reaper saying 'I'll see you soon'",
  "A slur comes out every time you burp OR every time you sneeze, you punch the closest person",
  "Hide and seek with Anne Frank OR call shotgun with Rosa Parks",
  "Hold up a 'Congrats on Heaven' sign at a funeral OR go to a spelling bee and heckle kids who get words wrong",
  "Tell a Make-A-Wish kid they're asking for too much OR eat a four course meal in front of starving children",
  "Complain about a bad haircut to a chemo patient OR tell a Holocaust survivor how much fun you had at camp",
  "Complain to a homeless person that your shower doesn't have enough water pressure OR tell a wheelchair user 'I get it' because your legs fall asleep sometimes",
  "Explain to a parent their child in war died through a knock knock joke OR throw a hamster off a bridge",
  "Your keyboard gets rearranged every day OR your mouse only moves in the opposite direction you move it",
  "Be the 71st man in the Bonnie Blue experience OR be second but the first guy friendly fires you",
  "Give a high five then a 'down low too slow' to the last place competitor in a Special Olympics race OR play 'quit hitting yourself' for 20 min with a quadriplegic",
  "Loudly and aggressively cum every time you sneeze OR make a random adult within 500ft of you loudly cum every time you hiccup",
  "Anytime you see a pregnant lady you have to play her stomach like bongos until one of her other kids cries OR anytime you see someone with a mental disability you have to copy it",
  "Come to a children's birthday party OR come on a children's birthday party",
  "Erase your worst memory OR relive your best one",
  "Be stuck in an endless day OR an eternal night",
  "Lose your best friend OR all your friends except your best one",
  "Save a stranger's life OR have a million dollars",
  "Never be able to leave your home OR be forever homeless",
  "Experience the pain of everyone you hurt OR have them feel all your pain",
  "Die painlessly alone OR painfully with loved ones around",
];

export const agreeData: string[] = [
  "Facetuning photos is completely fine",
  "I could date a girl that had a threesome with 2 other guys",
  "A man should pay for dinner on the first date",
  "It's okay to sleep with your friend's sister",
  "You can be friends with your ex",
  "I couldn't have a famous girlfriend",
  "I will try anything",
  "University is a waste of time and money",
  "If I were a social media influencer, I would be affected by trolls and hate comments",
  "Body count matters when choosing a partner",
  "It's okay for a 20 year old to date a 50 year old",
  "Most athletes are overpaid",
  "Not going down is a dealbreaker in a relationship",
  "Men should always be dominant",
  "Children get too many trophies",
  "Men should have a higher salary because they are mostly expected to pay for everything",
  "Phones should only be for people over the age of 15",
  "Money is more important than love",
  "Schools should make condoms available for students",
  "Schools should be allowed to ban certain books from their libraries",
  "We should incentivize 'fat' or 'obese' people to lose weight",
  "Men should be allowed to make laws that affect women's bodies",
  "The death penalty should be abolished",
  "Beauty pageants should be banned for sexism and sexualization",
  "Eat the rich",
];

export const beigeData: string[] = [
  "They set 15 alarms every morning starting from 5:00 AM, but still wake up at 7:30",
  "They narrate everything they're doing while cooking like it's a YouTube tutorial. 'And now we gently stir the onions...'",
  "Their favorite food is plain white bread. Not toast. Not with butter. Just bread.",
  "They refuse to watch the last episode of any show because they 'don't want it to end'",
  "They clap when a plane lands. Every time.",
  "They drink milk with every dinner — even with spicy food",
  "Their comfort watch is a crime documentary about unsolved murders. 'This just relaxes me.'",
  "They always say 'I could've done that' during magic shows. But they never do.",
  "They say 'oopsie' no matter how serious the mistake. 'Oopsie, I just deleted the entire file.'",
  "They always read the Wikipedia plot before watching a movie. 'I just like to know what I'm getting into.'",
  "They wave at animals. Like, all of them. Hi Mr. Squirrel!",
  "They set their GPS for places they know by heart — including their own house",
  "They refuse to update their phone until it physically stops working",
  "They have one mug for every drink — coffee, tea, juice, water, wine",
  "They refuse to kill bugs but also won't take them outside. Just cohabitates.",
  "They describe all music as 'vibey' — even metal or classical. 'Yeah, Bach is a total vibe.'",
  "They think expiration dates are suggestions. 'If it smells okay, it's fine.'",
  "They still say 'YOLO' unironically — especially for tiny decisions like getting a cookie",
  "They sleep with socks on and defend it like a personality trait",
  "They always 'accidentally' end up in conspiracy theory rabbit holes",
  "They refer to all pasta shapes as 'noodles'. 'You mean penne?' — 'No, the tube noodles.'",
  "They aggressively sort their M&Ms or Skittles by color before eating. Red first, always.",
  "They say 'let's circle back on that' — even in casual friend conversations",
  "They don't eat the last bite of their food because 'it feels like a goodbye'",
];

export const avoidData: { category: string; avoid: string | null }[] = [
  { category: "Streets in NYC", avoid: "14th St" },
  { category: "Pork dish", avoid: null },
  { category: "Car brand", avoid: "Honda" },
  { category: "Fortune 500 company", avoid: "Uber" },
  { category: "Gen 1 Pokémon", avoid: "Articuno" },
  { category: "Number from 1 to 25", avoid: "4" },
  { category: "Type of cheese", avoid: "Pepper Jack" },
  { category: "Article of clothing", avoid: "Jacket" },
  { category: "Vehicle", avoid: "Car" },
  { category: "Animal", avoid: "Lion" },
  { category: "Sport", avoid: "Volleyball" },
  { category: "European country", avoid: "Belgium" },
  { category: "African country", avoid: "Ethiopia" },
  { category: "Board game", avoid: "Sorry" },
  { category: "Social media app", avoid: "Instagram" },
  { category: "Premier League or NBA team", avoid: "Manchester United" },
  { category: "NFL quarterback (retired)", avoid: "Brees" },
  { category: "Vowel", avoid: null },
  { category: "Heads or tails?", avoid: "Heads" },
];

export const voteData: string[] = [
  "Who is most easily seduced?",
  "Who would be most upset if all their possessions were lost in a fire?",
  "Who would be first picked for a threesome?",
  "Who will marry someone who isn't born yet?",
  "Who would have the most interesting story to tell on the Jeremy Kyle Show?",
  "Who has a tattoo they regret?",
  "Who lost their virginity at the youngest age?",
  "Who believes money can buy happiness?",
  "Who can't spell illiterate?",
  "Who gives the most awkward hugs?",
  "Who's Google search history would you like to see the most?",
  "Who's real name would be the best pornstar name?",
  "Who's seen the most people in the room naked?",
  "Who has ended a night out in the hospital?",
  "Who would make $10,000 in commission the fastest as a used car salesman?",
  "Who spends the most time thinking about their ex?",
  "Whose closet is full of fake Burberry clothes?",
  "Who is the first in line for hell?",
  "Who would look best as the opposite gender?",
  "Who has gone the furthest in the back of a vehicle?",
  "Who will have a statue made in their honor?",
  "Who will be having the most sex in a retirement home?",
  "Who spends more time checking themselves out than working out at the gym?",
  "Who will be the last person alive?",
  "Who will get into a fight with an elderly person and lose?",
  "Who is late so often that you no longer show up on time for them?",
];

export const lntData: string[] = [
  "What's scarier: being alone or settling for the wrong person?",
  "What's the one 'what if' that keeps you awake at night?",
  "Do you think there's a part of you that you've lost?",
  "Who's the person you're afraid you're becoming?",
  "What's more painful: clinging to a toxic love or leaving someone you still care for but no longer love?",
  "What has been the saddest day of your life?",
  "Who was there for you when you were at your lowest?",
  "What do people assume about you that you wish was actually true?",
  "What do you need less of?",
  "What's something you wish you believed in but can't?",
  "Do you think your younger self would look up to you?",
  "What are you trying to prove to yourself?",
  "What was the worst nightmare of your life?",
  "When were you the most disappointed in yourself?",
  "Do you know what your purpose is?",
  "When you look back on your life at 80 years old, what do you think will matter the most?",
  "Do you like the person you're becoming?",
  "Have you ever hurt someone so badly that you still think about it?",
  "If you could live one day of your life over again, what day would you choose?",
  "What is standing between you and your happiness?",
  "If your life was a novel, how would you want your story to end?",
];

export const couplesData: string[] = [
  "If I lost my memory, what's the first thing you'd tell me about us?",
  "What does living a good life mean to you?",
  "What's your biggest fear about our future?",
  "Besides cheating and lying, what else destroys a relationship?",
  "What's your favorite weird habit of mine?",
  "What's an insecurity of mine that you love?",
  "Do you think there's a small sacrifice I made for you this month?",
  "Honestly, what do you think your 8 year old self would think of us?",
  "If your partner could only watch one TV series for the rest of their life, which one would they choose?",
  "Who'd be the first person your partner would call if they were in a desperate situation?",
  "Do you feel there's anything we need to improve in our relationship?",
  "Is there anything you need that I haven't been giving you?",
  "What aspects of your own personality or behavior cause friction in the relationship? What small steps could you take to reduce it?",
  "In what ways am I good for your mental health?",
  "What's the most comforting thing I've said that's stayed with you?",
  "How do our personalities complement each other?",
  "What's one thing you wish I asked you more about?",
  "Is there anything you want me to be more sensitive about?",
  "What do you miss most about our early days?",
  "What are you most afraid of others thinking about you?",
  "What's something I've helped you overcome?",
];

export const podcastData: string[] = [
  "You're in an arena surrounded by 5 year olds. No weapons, nowhere to go. Their mission is to take you out. How many can you take before they get you?",
  "If you could solve world peace in 3 steps, how would you do it?",
  "If you could bring one movie item to life, what would it be?",
  "What body part would you sell on the black market?",
  "How long would you stay in a microwave for $500,000 a second?",
  "If I have a meeting at 2pm and say 'let's move it forward 2 hours', what time is that?",
  "You are 1 of 999,999 people asked. You get to keep whatever 6-digit dollar amount you want as long as no one else chooses it. What do you choose?",
  "If you got a list of your stats once you died, which statistic would you be most curious about?",
  "6, 12, 18, 24 challenge in 24 hours: drink beers, finish, run laps, eat donuts — which order and how?",
  "You're in an arena with 50 hawks, 10 crocodiles, 3 brown bears, 15 wolves, 1 hunter with a rifle, 7 buffalo, 10,000 rats, 5 gorillas, 4 lions. Pick 2 to defend you. Goal: survive 1 hour.",
  "Your mom and your gf swap brains. The only way to swap them back is to sleep with one of them. What do you do?",
  "If Kanye started another holocaust, which album would slap the most in camp?",
];

export const uncomfortableData: string[] = [
  "What's the one thing you think I should let go of in my life, and why?",
  "What's a trait of mine that's hard for you to handle?",
  "Is there a moment you wish I'd supported you more?",
  "How do you really feel about how I handle conflicts?",
  "What's a change in me that worries you?",
  "What's the one thing about our relationship that you wish was different?",
  "What's the hardest thing about being open with me?",
];

export const categoriesData: string[] = [
  "Things in a fridge", "Types of pasta", "Bollywood actors", "NBA teams", "Things at a wedding",
  "Words that rhyme with 'cat'", "Countries in Europe", "Fast food chains", "Things at a beach",
  "Marvel superheroes", "Types of cheese", "Things that are yellow", "Premier League clubs",
  "Types of dances", "Things you do before bed", "Drake songs", "Types of alcohol",
  "New York City landmarks", "Things that make you cringe", "Olympic sports", "Reality TV shows",
  "Taylor Swift albums", "Indian dishes", "Things in a gym", "Car brands",
  "Things in a hospital", "Beyoncé songs", "Types of dogs", "Things that are red",
  "Animated movies", "Words that start with S", "Things on a first date",
  "Kardashian family members", "Things that are expensive", "Apple products",
  "Things at a gas station", "Nicknames for money", "Things you do when bored",
  "Board games", "Things that fly",
];

export const passwordData: string[] = [
  "Avocado", "Passport", "Microwave", "Sunburn", "Bluetooth", "Leftovers", "Mascara",
  "Quarterback", "Turbulence", "Hammock", "Fireworks", "Overtime", "Autopilot", "Curfew",
  "Blackout", "Carpool", "Headache", "Drought", "Postcard", "Deadline", "Sarcasm",
  "Gossip", "Bonfire", "Loophole", "Shortcut", "Bankrupt", "Brainstorm", "Comeback",
  "Detour", "Epidemic", "Freelance", "Grudge", "Humidity", "Irony", "Jealousy",
  "Kickback", "Landlord", "Meltdown", "Nostalgia", "Outbreak", "Paparazzi",
  "Quicksand", "Rivalry", "Scapegoat", "Trademark", "Underdog", "Vendetta", "Whiplash", "Exodus",
  "Alibi", "Detox",
];

export const overratedData: string[] = [
  "Avocado toast", "Sushi", "Pumpkin spice", "Brunch", "Charcuterie boards", "Truffle fries",
  "Kombucha", "Matcha", "New York pizza", "Wagyu beef", "Ranch dressing",
  "Paris", "Bali", "NYC", "Las Vegas", "Times Square", "Maldives", "Miami Beach",
  "Santorini", "Cancun all-inclusives", "Road trips",
  "The Godfather", "Breaking Bad", "Game of Thrones", "The Office", "Friends",
  "Marvel movies", "Coachella", "New Year's Eve", "Super Bowl halftime show",
  "Award shows", "TikTok", "Instagram Reels",
  "Cold plunges", "Therapy", "Journaling", "Working from home", "Gym culture",
  "Astrology", "Manifestation", "Side hustles", "Networking events", "Crypto",
  "NFTs", "Meal prepping", "Morning routines", "Hustle culture",
  "Elon Musk", "LeBron vs Jordan debate", "College degrees", "Homeownership",
  "Marriage", "Having kids", "Black Friday", "Apple products", "Luxury brands",
];

export const twentyqData: string[] = [
  "🎬 A character from a movie or TV show",
  "🏆 A famous athlete (active or retired)",
  "🌍 A country, city, or landmark",
  "🍕 A food or drink",
  "🎵 A musician, band, or song",
  "📱 A brand or product",
  "🦁 An animal",
  "🎮 A video game or video game character",
  "👟 Something you can wear",
  "🏠 Something you'd find in a house",
  "🌟 A Bollywood actor or movie",
  "⚽ A sports team or tournament",
  "📚 A book, character, or author",
  "🚗 A vehicle or mode of transport",
  "💼 A job or profession",
  "🤣 A meme or internet moment",
  "🎭 A historical figure",
  "🪐 Something from outer space",
  "🏖️ Something at the beach",
  "🎉 Something at a party",
];

export const wavelengthData: { left: string; right: string }[] = [
  { left: "Cold", right: "Hot" },
  { left: "Boring", right: "Exciting" },
  { left: "Healthy", right: "Unhealthy" },
  { left: "Cheap", right: "Expensive" },
  { left: "Safe", right: "Dangerous" },
  { left: "Ugly", right: "Beautiful" },
  { left: "Weak", right: "Powerful" },
  { left: "Simple", right: "Complex" },
  { left: "Quiet", right: "Loud" },
  { left: "Old", right: "New" },
  { left: "Useless", right: "Essential" },
  { left: "Overrated", right: "Underrated" },
  { left: "Fake", right: "Authentic" },
  { left: "Forgettable", right: "Iconic" },
  { left: "Sad", right: "Happy" },
  { left: "Slow", right: "Fast" },
  { left: "Soft", right: "Hard" },
  { left: "Rare", right: "Common" },
  { left: "Smart", right: "Dumb" },
  { left: "Innocent", right: "Guilty" },
  { left: "Natural", right: "Artificial" },
  { left: "Introverted", right: "Extroverted" },
  { left: "Romantic", right: "Unromantic" },
  { left: "Childish", right: "Mature" },
  { left: "Dark", right: "Light" },
  { left: "Gross", right: "Delicious" },
  { left: "Relaxing", right: "Stressful" },
  { left: "Private", right: "Public" },
  { left: "Lucky", right: "Unlucky" },
  { left: "Trendy", right: "Timeless" },
  { left: "Mainstream", right: "Niche" },
  { left: "Selfish", right: "Generous" },
  { left: "Cruel", right: "Kind" },
  { left: "Rational", right: "Emotional" },
  { left: "Predictable", right: "Unpredictable" },
  { left: "Fragile", right: "Tough" },
  { left: "Satisfying", right: "Disappointing" },
  { left: "Trustworthy", right: "Suspicious" },
  { left: "Serious", right: "Funny" },
  { left: "Cringey", right: "Cool" },
  { left: "Offensive", right: "Wholesome" },
  { left: "Classy", right: "Trashy" },
  { left: "Spontaneous", right: "Planned" },
  { left: "Passive", right: "Aggressive" },
  { left: "Lazy", right: "Hardworking" },
  { left: "Low key", right: "Extra" },
  { left: "Fiction", right: "Reality" },
  { left: "Short-lived", right: "Legendary" },
  { left: "Basic", right: "Unique" },
  { left: "Nerdy", right: "Cool" },
  { left: "Uncomfortable", right: "Cozy" },
  { left: "Risky", right: "Safe bet" },
  { left: "Chaotic", right: "Organized" },
  { left: "Fleeting", right: "Eternal" },
  { left: "Underground", right: "Mainstream" },
  { left: "Subtle", right: "Obvious" },
  { left: "Forgiven", right: "Unforgivable" },
  { left: "Cliché", right: "Original" },
  { left: "Tame", right: "Wild" },
  { left: "Amateur", right: "Professional" },
];

export const fivesecData: string[] = [
  "Name 3 things in a bathroom",
  "Name 3 things you do when bored",
  "Name 3 fast food restaurants",
  "Name 3 sports you can play alone",
  "Name 3 things you find in a wallet",
  "Name 3 countries in Asia",
  "Name 3 things that are blue",
  "Name 3 types of cheese",
  "Name 3 Taylor Swift songs",
  "Name 3 things at a wedding",
  "Name 3 things you can do with ice",
  "Name 3 celebrity couples",
  "Name 3 things at a gas station",
  "Name 3 words that rhyme with 'time'",
  "Name 3 Marvel superheroes",
  "Name 3 things in a hospital room",
  "Name 3 things you wear at the gym",
  "Name 3 breakfast foods",
  "Name 3 things that are black and white",
  "Name 3 car brands",
  "Name 3 animals that can swim",
  "Name 3 things you take on a flight",
  "Name 3 things in a toolbox",
  "Name 3 Kanye West albums",
  "Name 3 things that are sticky",
  "Name 3 Drake songs",
  "Name 3 things that float",
  "Name 3 countries in Africa",
  "Name 3 things you'd find at a bonfire",
  "Name 3 types of pasta",
  "Name 3 things older than you",
  "Name 3 words that start with Q",
  "Name 3 things in outer space",
  "Name 3 apps on your phone right now",
  "Name 3 things you can do in 5 seconds",
  "Name 3 dances",
  "Name 3 types of alcohol",
  "Name 3 Bollywood actors",
  "Name 3 things that make noise",
  "Name 3 Olympic sports",
  "Name 3 things that are round",
  "Name 3 things in a school bag",
  "Name 3 things you'd text your best friend",
  "Name 3 things that are spicy",
  "Name 3 NBA teams",
  "Name 3 animated movies",
  "Name 3 things in a kitchen drawer",
  "Name 3 reality TV shows",
  "Name 3 things at a beach",
  "Name 3 things that smell good",
  "Name 3 words that rhyme with 'night'",
  "Name 3 things a dentist uses",
  "Name 3 things associated with summer",
  "Name 3 Premier League clubs",
  "Name 3 things you'd bring to a desert island",
  "Name 3 bad excuses for being late",
  "Name 3 things you'd find in a purse",
  "Name 3 types of dogs",
  "Name 3 things that are magnetic",
  "Name 3 cocktails",
  "Name 3 things associated with New Year's Eve",
  "Name 3 things in the sky at night",
  "Name 3 things that are sour",
  "Name 3 phrases that mean 'yes'",
  "Name 3 things you'd say on a first date",
  "Name 3 things hotter than the sun (jokes welcome)",
  "Name 3 things on a restaurant menu",
  "Name 3 words your parents use that you never would",
  "Name 3 things you've lied about",
  "Name 3 things that can go viral",
  "Name 3 things to never do at a funeral",
  "Name 3 things that belong in a horror movie",
  "Name 3 excuses to leave a party early",
  "Name 3 things people do but won't admit",
  "Name 3 ways to know someone is lying",
  "Name 3 things that get better with age",
  "Name 3 things you'd never eat for breakfast",
  "Name 3 things that give you anxiety",
  "Name 3 famous redheads",
];

export interface ContentSeed {
  game_id: string;
  content: string;
  content_b: string | null;
  category: string | null;
  answer: string | null;
  sort_order: number;
}

// Flattens every game's default data into game_content rows.
export function buildContentRows(): ContentSeed[] {
  const rows: ContentSeed[] = [];

  const pushSimple = (gameId: string, items: string[]) =>
    items.forEach((content, i) =>
      rows.push({ game_id: gameId, content, content_b: null, category: null, answer: null, sort_order: i })
    );

  triviaData.forEach((t, i) =>
    rows.push({ game_id: "trivia", content: t.q, content_b: null, category: t.type, answer: t.a, sort_order: i })
  );

  pushSimple("wyr", wyrData);
  pushSimple("agree", agreeData);
  pushSimple("beige", beigeData);
  pushSimple("vote", voteData);
  pushSimple("lnt", lntData);
  pushSimple("couples", couplesData);
  pushSimple("podcast", podcastData);
  pushSimple("uncomfortable", uncomfortableData);
  pushSimple("categories", categoriesData);
  pushSimple("password", passwordData);
  pushSimple("overrated", overratedData);
  pushSimple("twentyq", twentyqData);

  avoidData.forEach((a, i) =>
    rows.push({ game_id: "avoid", content: a.category, content_b: a.avoid, category: null, answer: null, sort_order: i })
  );

  wavelengthData.forEach((w, i) =>
    rows.push({ game_id: "wavelength", content: w.left, content_b: w.right, category: null, answer: null, sort_order: i })
  );

  pushSimple("fivesec", fivesecData);

  return rows;
}

// Default content rows for a single built-in game (used by admin "Reset").
export function defaultRowsFor(gameId: string): ContentSeed[] {
  return buildContentRows().filter((r) => r.game_id === gameId);
}

export const BUILTIN_IDS = new Set(BUILTIN_GAMES.map((g) => g.id));
